"""
Every packaging version home tracks `sunglasses.__version__`.

The release version is written down in more places than anything checks. Two
of them were found unguarded on 2026-09-20 during the beta-readiness sweep:

  * `setup.py`'s `version=` literal — it NAMES THE BUILT WHEEL, and nothing
    derives it from `__version__` (T8). Bump the other files and leave this
    one and CI goes green over a wheel still called 0.5.9.
  * `server.json`, the MCP registry manifest, which pins the version TWICE
    (top level and `packages[0]`). Nothing in the repo, in `.github/` or in
    the ship skill reads, validates or bumps it, so the registry entry would
    advertise 0.5.9 against a PyPI serving 0.6.0 — silently (row 6).

The homes that already had a gate are deliberately not re-checked here: the
git tag is enforced by `release.yml` (it refuses a tag that is not equal to
`sunglasses.__version__`) and the CHANGELOG heading by the readiness doc.

`stats/current.json` also carries a version and is NOT included: it is
generated by `tools/gen_language_stats.py` / `gen_perf_stats.py` and is not in
`MANIFEST.in`, so it ships in no wheel. It belongs to the site-stats lane, not
to packaging. If that ever changes, add it here.

`check()` is a pure function over already-read values, so it can be aimed at
mutated inputs. The negative controls at the bottom are what prove the reader
can fail: a version check that cannot REACH the value it compares passes for
the wrong reason, which is worse than no check at all.
"""
from __future__ import annotations

import ast
import json
from pathlib import Path

import pytest

import sunglasses

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "server.json"
SETUP = ROOT / "setup.py"


def setup_version(source: str) -> str | None:
    """The `version=` literal passed to setup(), read WITHOUT executing setup.py.

    Returns None if there is no such literal — which `check` treats as a
    problem, not as permission to skip.
    """
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        name = node.func.attr if isinstance(node.func, ast.Attribute) else getattr(node.func, "id", None)
        if name != "setup":
            continue
        for kw in node.keywords:
            if kw.arg == "version" and isinstance(kw.value, ast.Constant):
                return kw.value.value
    return None


def version_homes(setup_src: str, manifest: dict) -> list[tuple[str, str | None]]:
    """(label, value) for every packaging home. A value of None means 'absent'."""
    homes: list[tuple[str, str | None]] = [
        ("setup.py version= (names the built wheel)", setup_version(setup_src)),
        ("server.json top-level version", manifest.get("version")),
    ]

    packages = manifest.get("packages")
    if not isinstance(packages, list) or not packages:
        # Without this the comprehension below yields nothing and the whole
        # manifest half of the gate silently disappears. That is the failure
        # mode, so it is reported as a home that could not be read.
        homes.append(("server.json packages[] (missing or empty)", None))
        return homes

    pypi = [p for p in packages if p.get("registryType") == "pypi"]
    if not pypi:
        homes.append(("server.json pypi package entry (absent)", None))
        return homes

    for entry in pypi:
        ident = entry.get("identifier", "<no identifier>")
        homes.append((f"server.json packages[{ident!r}].version", entry.get("version")))

    return homes


def check(homes: list[tuple[str, str | None]], version: str) -> list[str]:
    """Every reason these homes do not all name `version`. Empty list == good."""
    problems = []
    for label, got in homes:
        if got is None:
            problems.append(f"{label}: no version found at all")
        elif got != version:
            problems.append(f"{label}: {got!r}, expected {version!r}")
    return problems


def _real_homes():
    assert SETUP.is_file(), f"{SETUP} is missing"
    assert MANIFEST.is_file(), (
        f"{MANIFEST} is missing. This is a gate on that file, not an optional "
        f"extra — do not delete the manifest to make the test pass."
    )
    return version_homes(
        SETUP.read_text(encoding="utf-8"),
        json.loads(MANIFEST.read_text(encoding="utf-8")),
    )


def test_every_version_home_names_the_version_the_package_declares():
    """THE gate: setup.py and both server.json pins track sunglasses.__version__."""
    problems = check(_real_homes(), sunglasses.__version__)
    assert not problems, (
        f"packaging files disagree with sunglasses.__version__ "
        f"({sunglasses.__version__}):\n  " + "\n  ".join(problems) +
        "\n\nBumping the release means bumping ALL of them: sunglasses/__init__.py, "
        "setup.py's version= (it names the built wheel), and server.json's "
        "top-level version AND packages[].version. Nothing else will remind you."
    )


def test_all_three_packaging_homes_are_actually_found():
    """The premise. If a home moves or disappears, this says so instead of passing."""
    labels = [label for label, _ in _real_homes()]
    assert len(labels) == 3, f"expected 3 packaging version homes, found {len(labels)}: {labels}"
    assert any("setup.py" in l for l in labels)
    assert sum("server.json" in l for l in labels) == 2


# --- negative controls: proof the reader can fail ---------------------------
# Each row is a real way the version can drift. If any comes back clean, the
# gate above is decorative.

SETUP_SRC = """
from setuptools import setup
setup(name="sunglasses", version="0.5.9", packages=["sunglasses"])
"""

MANIFEST_DOC = {
    "version": "0.5.9",
    "packages": [{"registryType": "pypi", "identifier": "sunglasses", "version": "0.5.9"}],
}


def _mutate(setup_src=None, manifest=None):
    import copy
    return version_homes(
        setup_src if setup_src is not None else SETUP_SRC,
        copy.deepcopy(manifest) if manifest is not None else copy.deepcopy(MANIFEST_DOC),
    )


@pytest.mark.parametrize(
    "homes,because",
    [
        (_mutate(setup_src=SETUP_SRC.replace('version="0.5.9"', 'version="0.6.0"')),
         "setup.py bumped alone — the wheel would be named 0.6.0, the rest 0.5.9"),
        (_mutate(setup_src='from setuptools import setup\nsetup(name="sunglasses")\n'),
         "setup.py has no version= at all"),
        (_mutate(manifest={**MANIFEST_DOC, "version": "0.6.0"}),
         "server.json top-level bumped, package left behind"),
        (_mutate(manifest={"version": "0.5.9",
                           "packages": [{"registryType": "pypi", "identifier": "sunglasses",
                                         "version": "0.6.0"}]}),
         "server.json package bumped, top-level left behind"),
        (_mutate(manifest={"packages": MANIFEST_DOC["packages"]}),
         "server.json top-level pin deleted"),
        (_mutate(manifest={"version": "0.5.9",
                           "packages": [{"registryType": "pypi", "identifier": "sunglasses"}]}),
         "server.json package pin deleted"),
        (_mutate(manifest={"version": "0.5.9", "packages": []}),
         "packages emptied — the manifest half would silently vanish"),
        (_mutate(manifest={"version": "0.5.9",
                           "packages": [{"registryType": "npm", "version": "0.5.9"}]}),
         "the pypi entry is gone"),
    ],
)
def test_the_reader_catches_each_way_a_version_home_can_drift(homes, because):
    problems = check(homes, "0.5.9")
    assert problems, f"check() returned clean on a bad tree: {because}"


def test_the_reader_is_clean_on_a_consistent_tree():
    """The positive control the mutations are measured against."""
    assert check(_mutate(), "0.5.9") == []


def test_setup_version_reads_the_literal_without_executing_setup_py():
    assert setup_version(SETUP_SRC) == "0.5.9"
    assert setup_version("x = 1\n") is None


def test_the_release_that_forgets_setup_py_is_caught():
    """The exact shape T8 measured on 2026-09-20.

    The three named files get bumped for the release and `setup.py` is
    forgotten, so every other check goes green over a wheel still called
    0.5.9. Target version is 0.6.0 here, so the ONE home that must be flagged
    is setup.py — checking against 0.5.9 instead would flag the manifest and
    pass for the wrong reason.
    """
    homes = version_homes(
        SETUP_SRC,                                   # still 0.5.9
        {"version": "0.6.0",
         "packages": [{"registryType": "pypi", "identifier": "sunglasses",
                       "version": "0.6.0"}]},
    )
    problems = check(homes, "0.6.0")
    assert len(problems) == 1, problems
    assert "setup.py" in problems[0], problems[0]
    assert "names the built wheel" in problems[0]
