#!/usr/bin/env python3
"""Generate the v0.5.6 acceptance case table from the SAME module the tests read.

The point is not the table, it is the shared source. A hand-maintained table can
claim coverage the suite does not assert -- which is exactly how two review
rounds of hand-picked cases both read as complete and both missed the next five
samples. Here the table and the tests are two renderings of tests/v056_matrix.py,
so a cell cannot be asserted without appearing, or appear without being asserted.

    python3 tools/gen_v056_matrix_table.py > V056_ACCEPTANCE_MATRIX.md
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "tests"))
import v056_matrix as M  # noqa: E402

_CELL = {
    "clean": "0 clean",
    "threat": "1 threat",
    "threat_incomplete": "1 threat+incomplete",
    "incomplete": "3 incomplete",
    "operational": "2 operational",
}

# Round 4: "N/A" used to do four different jobs in this table, which is most of
# why ASTRA read it as a coverage argument it could not check. Each kind now
# renders differently, and each has its own section below.
#   `outcome`  asserted
#   `≡ state`  asserted, driven with another state's input (a labelled alias)
#   `N/A`      the state cannot exist on this surface -- reason given
#   `⇄`        additionally compared, by execution, against the surface it wraps


def _mutation_counts():
    """Count the mutation cases and controls FROM THE SOURCE, never by hand.

    A hand-typed denominator beside a generated table is the same defect the
    receipt was pulled up for: it is right on the day it is written and silently
    wrong afterwards. These are read out of the test module itself.
    """
    import ast

    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "tests", "test_v056_matrix.py")
    tree = ast.parse(open(path).read())

    mutations = controls = 0
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "_MUTATIONS":
                    mutations = len(node.value.elts)
        if (isinstance(node, ast.FunctionDef)
                and node.name == "test_the_mutations_are_mutations_of_something_that_passes"):
            for sub in ast.walk(node):
                if (isinstance(sub, ast.Assign) and isinstance(sub.targets[0], ast.Name)
                        and sub.targets[0].id == "good"):
                    controls = len(sub.value.elts)
    if not mutations or not controls:  # pragma: no cover - the guard IS the point
        raise SystemExit("could not read the mutation/control counts from the test "
                         "module; refusing to publish a hand-typed denominator")
    return mutations, controls


def main() -> int:
    counts = M.coverage_counts()
    out = []
    w = out.append

    w("# v0.5.6 — acceptance matrix (surface × state)")
    w("")
    w("> Generated by `tools/gen_v056_matrix_table.py` from `tests/v056_matrix.py`,")
    w("> which is the same module `tests/test_v056_matrix.py` parametrizes over.")
    w("> Do not edit this file by hand: regenerate it.")
    w("")
    w(f"**{counts['asserted']} asserted cells · {counts['na']} N/A with a stated reason · "
      f"{counts['total']} total**, of which {counts['alias']} are labelled aliases and")
    w(f"{counts['equivalences']} additionally assert an executed equivalence against the")
    w("surface they wrap. Each asserted cell runs the surface in every output")
    w("format it supports and checks: the three axes present and mutually consistent")
    w("(`is_clean == not threat_found and inspection_complete`), exactly one document on")
    w("stdout (or `isError` for MCP), the HUMAN outcome line saying the same thing the")
    w("axes say, SARIF carrying `properties.inspectionComplete` whenever coverage is")
    w("partial, and no traceback on any path.")
    w("")
    w("**What this table cannot prove, and what does.** A table generated from the")
    w("declarations proves the table and the tests read the same source. It cannot")
    w("prove the tests assert anything -- ASTRA demonstrated exactly that by replacing")
    muts, controls = _mutation_counts()
    w("one cell's human output with `CLEAN. All content was inspected.` and watching")
    w(f"the cell still pass. So `tests/test_v056_matrix.py` carries {muts} MUTATION cases:")
    w("for every outcome and format, a response with its coverage evidence stripped is")
    w("fed to the same assertion functions the real cells use, and each must FAIL --")
    w(f"plus {controls} unmutated controls that must PASS, so the mutation suite cannot be")
    w("satisfied by assertions that reject everything. No cell may skip: a grid-level")
    w("test asserts generated cells == declared non-N/A cells, exactly.")
    w("")
    w("Outcome vocabulary — exit code and the axes it implies:")
    w("")
    w("| outcome | exit | threat_found | inspection_complete | is_clean |")
    w("|---|---|---|---|---|")
    for name, spec in M.OUTCOMES.items():
        fmt = lambda v: "—" if v is None else ("T" if v else "F")
        w(f"| `{name}` | {spec['exit']} | {fmt(spec['threat_found'])} | "
          f"{fmt(spec['inspection_complete'])} | {fmt(spec['is_clean'])} |")
    w("")
    w("## States")
    w("")
    w("| state | meaning |")
    w("|---|---|")
    for sid, label, desc in M.STATES:
        w(f"| **{label}** (`{sid}`) | {desc} |")
    w("")
    w("## The matrix")
    w("")

    header = "| surface | " + " | ".join(label for _s, label, _d in M.STATES) + " |"
    w(header)
    w("|---" * (len(M.STATES) + 1) + "|")

    for sid, group, label, formats, in_states in (
            (s[0], s[1], s[2], s[3], None) for s in M.SURFACES):
        cells = []
        for state, _sl, _sd in M.STATES:
            value = M.MATRIX[(sid, state)]
            if M.is_na(value):
                cells.append(f"N/A ({value.claim})")
            else:
                mark = " ⚠" if (sid, state) in M.NOTES else ""
                if (sid, state) in M.EQUIVALENCE:
                    mark += " ⇄"
                if M.is_alias(value):
                    # the outcome is whatever the ALIAS TARGET asserts on this surface
                    target = M.MATRIX[(sid, value.state)]
                    cells.append(f"{_CELL[target]} ≡`{value.state}`{mark}")
                else:
                    cells.append(_CELL[value] + mark)
        w(f"| **{label}**<br>`{'`, `'.join(formats)}` | " + " | ".join(cells) + " |")

    w("")
    w("## N/A cells, and why each one cannot exist")
    w("")
    w("An omitted cell and a covered cell look identical in a table. These are the")
    w("cells the space does not contain, each with a claim a reviewer can check.")
    w("")
    w("Each reason declares WHAT KIND of argument it is, because \"N/A\" was being")
    w("used for four different arguments and a reviewer could not tell which:")
    w("")
    w("| claim | means |")
    w("|---|---|")
    for kind, meaning in M.NA_CLAIMS.items():
        w(f"| `{kind}` | {meaning} |")
    w("")
    w("| surface | state | claim | reason |")
    w("|---|---|---|---|")
    for sid, _g, label, _f, state, value in M.cells():
        if M.is_na(value):
            w(f"| {label} | `{state}` | `{value.claim}` | {value.why} |")

    aliases = [(label, state, value) for _s, _g, label, _f, state, value
               in M.cells() if M.is_alias(value)]
    if aliases:
        w("")
        w("## Aliased cells — asserted, but not independent evidence")
        w("")
        w("The state exists on this surface and the cell RUNS; its input is simply")
        w("the same input another state already describes. Labelling them stops the")
        w("count from reading as more coverage than it is.")
        w("")
        w("| surface | state | driven as | why they are the same input |")
        w("|---|---|---|---|")
        for label, state, value in aliases:
            w(f"| {label} | `{state}` | `{value.state}` | {value.why} |")

    if M.EQUIVALENCE:
        w("")
        w("## Equivalences — proven by execution, not by name")
        w("")
        w("ASTRA: *\"Direct wrappers can use proven equivalence mappings; distinct")
        w("aggregates cannot inherit coverage by name.\"* For each row below the test")
        w("runs BOTH surfaces on the same input and requires the same exit code and")
        w("the same three axes. A wrapper that disagrees with what it wraps is a")
        w("second implementation, and this is how we find out.")
        w("")
        w("| surface | state | must match |")
        w("|---|---|---|")
        labels_e = {s[0]: s[2] for s in M.SURFACES}
        for (sid, state), twin in sorted(M.EQUIVALENCE.items()):
            w(f"| {labels_e[sid]} | `{state}` | {labels_e[twin]} |")
    if M.NOTES:
        w("")
        w("## Asserted cells that carry a caveat")
        w("")
        w("Behaviour that is truthful but differs from a sibling surface. It is")
        w("recorded here rather than hidden in an N/A or asserted silently.")
        w("")
        w("| surface | state | note |")
        w("|---|---|---|")
        labels = {s[0]: s[2] for s in M.SURFACES}
        for (sid, state), note in M.NOTES.items():
            w(f"| {labels[sid]} | `{state}` | {note} |")
    w("")
    w("## Reproduce")
    w("")
    w("```sh")
    w("python3 -m pytest tests/test_v056_matrix.py -q     # one test per asserted cell")
    w("python3 tools/gen_v056_matrix_table.py             # regenerates this file")
    w("```")

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
