#!/usr/bin/env python3
"""Generate the v0.5.6 acceptance case table from the SAME module the tests read.

The point is not the table, it is the shared source. A hand-maintained table can
claim coverage the suite does not assert -- which is exactly how two review
rounds of hand-picked cases both read as complete and both missed the next five
samples. Here the table and the tests are two renderings of tests/v056_matrix.py,
so a cell cannot be asserted without appearing, or appear without being asserted.

    python3 tools/gen_v056_matrix_table.py > V056_ACCEPTANCE_MATRIX.md
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "tests"))
import v056_matrix as M  # noqa: E402

_CELL = {
    "clean": "0 clean",
    "threat": "1 threat",
    "threat_incomplete": "1 threat+incomplete",
    "incomplete": "3 incomplete",
    "operational": "2 operational",
}


def main() -> int:
    counts = M.coverage_counts()
    out = []
    w = out.append

    w("# v0.5.6 — acceptance matrix (surface × state)")
    w("")
    w("> Generated by `tools/gen_v056_matrix_table.py` from `tests/v056_matrix.py`,")
    w("> which is the same module `tests/test_v056_matrix.py` parametrizes over.")
    w("> Do not edit this file by hand: regenerate it.")
    w("")
    w(f"**{counts['asserted']} asserted cells · {counts['na']} N/A with a stated reason · "
      f"{counts['total']} total.** Each asserted cell runs the surface in every output")
    w("format it supports and checks: the three axes present and mutually consistent")
    w("(`is_clean == not threat_found and inspection_complete`), exactly one document on")
    w("stdout (or `isError` for MCP), SARIF carrying `properties.inspectionComplete`")
    w("whenever coverage is partial, and no traceback on any path.")
    w("")
    w("Outcome vocabulary — exit code and the axes it implies:")
    w("")
    w("| outcome | exit | threat_found | inspection_complete | is_clean |")
    w("|---|---|---|---|---|")
    for name, spec in M.OUTCOMES.items():
        fmt = lambda v: "—" if v is None else ("T" if v else "F")
        w(f"| `{name}` | {spec['exit']} | {fmt(spec['threat_found'])} | "
          f"{fmt(spec['inspection_complete'])} | {fmt(spec['is_clean'])} |")
    w("")
    w("## States")
    w("")
    w("| state | meaning |")
    w("|---|---|")
    for sid, label, desc in M.STATES:
        w(f"| **{label}** (`{sid}`) | {desc} |")
    w("")
    w("## The matrix")
    w("")

    header = "| surface | " + " | ".join(label for _s, label, _d in M.STATES) + " |"
    w(header)
    w("|---" * (len(M.STATES) + 1) + "|")

    for sid, group, label, formats, in_states in (
            (s[0], s[1], s[2], s[3], None) for s in M.SURFACES):
        cells = []
        for state, _sl, _sd in M.STATES:
            value = M.MATRIX[(sid, state)]
            if M.is_na(value):
                cells.append("N/A")
            else:
                mark = " ⚠" if (sid, state) in M.NOTES else ""
                cells.append(_CELL[value] + mark)
        w(f"| **{label}**<br>`{'`, `'.join(formats)}` | " + " | ".join(cells) + " |")

    w("")
    w("## N/A cells, and why each one cannot exist")
    w("")
    w("An omitted cell and a covered cell look identical in a table. These are the")
    w("cells the space does not contain, each with a claim a reviewer can check.")
    w("")
    w("| surface | state | reason |")
    w("|---|---|---|")
    for sid, _g, label, _f, state, value in M.cells():
        if M.is_na(value):
            w(f"| {label} | `{state}` | {value[1]} |")
    if M.NOTES:
        w("")
        w("## Asserted cells that carry a caveat")
        w("")
        w("Behaviour that is truthful but differs from a sibling surface. It is")
        w("recorded here rather than hidden in an N/A or asserted silently.")
        w("")
        w("| surface | state | note |")
        w("|---|---|---|")
        labels = {s[0]: s[2] for s in M.SURFACES}
        for (sid, state), note in M.NOTES.items():
            w(f"| {labels[sid]} | `{state}` | {note} |")
    w("")
    w("## Reproduce")
    w("")
    w("```sh")
    w("python3 -m pytest tests/test_v056_matrix.py -q     # one test per asserted cell")
    w("python3 tools/gen_v056_matrix_table.py             # regenerates this file")
    w("```")

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
