#!/usr/bin/env python3
"""Produce the published byte vectors two independent implementations agree on.

ASTRA: "Publish exact byte vectors for hashes, signatures and fingerprint
derivation before implementing both writer and verifier." This generates them
from `wire.py` itself, so the specification and the code cannot drift: if
someone changes a domain prefix, the vectors change in the same commit and the
diff says so out loud.

The signing key here is a FIXED, PUBLISHED test seed. It is a test vector, not
a secret, and it is written down precisely so an independent implementation can
reproduce every signature below byte for byte. No real key is ever used to
generate documentation.

Run:  python3 make_vectors.py > VECTORS.json
"""
from __future__ import annotations

import json
import sys

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed25519

import wire

# A published test seed. Never a real key: this one exists to be copied.
TEST_SEED = bytes(range(32))

GENESIS = {
    "chain_id": "chain-test-0001",
    "event": "genesis",
    "key_id": "key-test-0001",
    "prev_hash": None,
    "seq": 0,
    "wire": wire.WIRE_VERSION,
}

EVENT = {
    "chain_id": "chain-test-0001",
    "event": "decision",
    "key_id": "key-test-0001",
    "prev_hash": None,          # filled from the genesis hash below
    "seq": 1,
    "wire": wire.WIRE_VERSION,
}

CHECKPOINT = {
    "chain_id": "chain-test-0001",
    "covered_head": None,       # filled from the event hash below
    "covered_seq": 1,
    "event": "checkpoint",
    "interval": 100,
    "key_id": "key-test-0001",
    "prev_hash": None,          # filled from the event hash below
    "purpose": "interval",
    "seq": 2,
    "wire": wire.WIRE_VERSION,
}


def build() -> dict:
    private = ed25519.Ed25519PrivateKey.from_private_bytes(TEST_SEED)
    public = private.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw)

    genesis_line = wire.encode(GENESIS)
    genesis_hash = wire.record_hash(genesis_line)

    event = dict(EVENT, prev_hash=genesis_hash)
    event_line = wire.encode(event)
    event_hash = wire.record_hash(event_line)

    # The covered head is the PREVIOUS record's hash, and the completed signed
    # checkpoint becomes the next predecessor.
    checkpoint = dict(CHECKPOINT, prev_hash=event_hash, covered_head=event_hash)
    signing_bytes = wire.checkpoint_signing_bytes(checkpoint)
    signature = private.sign(signing_bytes)
    signed = dict(checkpoint, signature=signature.hex())
    signed_line = wire.encode(signed)

    return {
        "note": "Generated by make_vectors.py from wire.py. The seed is a "
                "published test value and never a real key.",
        "wire_version": wire.WIRE_VERSION,
        "hash_algorithm": wire.HASH_ALGORITHM,
        "signature_algorithm": wire.SIGNATURE_ALGORITHM,
        "domains": {
            "record": wire.RECORD_DOMAIN.decode("latin-1"),
            "record_hex": wire.RECORD_DOMAIN.hex(),
            "checkpoint": wire.CHECKPOINT_DOMAIN.decode("latin-1"),
            "checkpoint_hex": wire.CHECKPOINT_DOMAIN.hex(),
            "fingerprint": wire.FINGERPRINT_DOMAIN.decode("latin-1"),
            "fingerprint_hex": wire.FINGERPRINT_DOMAIN.hex(),
        },
        "key": {
            "seed_hex": TEST_SEED.hex(),
            "public_hex": public.hex(),
            "fingerprint": wire.key_fingerprint(public),
        },
        "records": {
            "genesis": {
                "record": GENESIS,
                "line_hex": genesis_line.hex(),
                "line_utf8": genesis_line.decode("utf-8"),
                "chain_hash": genesis_hash,
            },
            "event": {
                "record": event,
                "line_hex": event_line.hex(),
                "line_utf8": event_line.decode("utf-8"),
                "chain_hash": event_hash,
            },
            "checkpoint": {
                "record_unsigned": checkpoint,
                "signing_bytes_hex": signing_bytes.hex(),
                "signature_hex": signature.hex(),
                "record_signed": signed,
                "line_hex": signed_line.hex(),
                "line_utf8": signed_line.decode("utf-8"),
                "chain_hash": wire.record_hash(signed_line),
            },
        },
    }


if __name__ == "__main__":
    json.dump(build(), sys.stdout, indent=1, sort_keys=True)
    sys.stdout.write("\n")
